# Generated by Django 5.0.4 on 2024-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
