# Generated by Django 5.0.4 on 2024-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contract_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contact_info',
            new_name='address',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_doc',
            field=models.FileField(blank=True, default=None, upload_to='contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
