# Generated by Django 5.0.4 on 2024-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_contact_info_contract_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
