# Generated by Django 5.0.4 on 2024-05-07 16:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_transaction_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_doc',
            field=models.FileField(blank=True, default=None, storage=django.core.files.storage.FileSystemStorage(location='/home/alex/data/personal/kollektiivi/website/accounts/'), upload_to=''),
        ),
    ]
