# Generated by Django 4.2.1 on 2023-06-21 20:26

import tinymce.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField()),
                ('slug', models.SlugField()),
                ('body', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, default=None, upload_to='images')),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
