# Generated by Django 4.2.1 on 2023-06-22 17:59

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='body_fi',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_fi',
            field=models.TextField(null=True),
        ),
    ]
