# Generated by Django 4.2.1 on 2023-06-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_body_en_blog_body_fi_blog_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default=None),
        ),
    ]
