# Generated by Django 4.2.1 on 2023-06-24 16:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body_fi',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
