# Generated by Django 4.2.7 on 2023-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='title_fi',
            field=models.TextField(null=True),
        ),
    ]
