# Generated by Django 4.2.7 on 2023-11-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postattachment_title_en_postattachment_title_fi'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
