# Generated by Django 4.2.1 on 2023-06-21 20:26

import tinymce.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_fi', models.CharField(max_length=200, null=True)),
                ('menu_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('menu_title_en', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('menu_title_fi', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('body', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('body_en', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('body_fi', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('slug', models.SlugField()),
                ('menu_order_by', models.IntegerField(default=0)),
                ('on_menu', models.BooleanField(default=False)),
                ('on_footer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('name_en', models.TextField(null=True)),
                ('name_fi', models.TextField(null=True)),
                ('description', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('description_en', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('description_fi', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('slug', models.SlugField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip', models.GenericIPAddressField()),
                ('agent', models.TextField(blank=True)),
                ('url', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Tracker',
                'verbose_name_plural': 'Trackers',
            },
        ),
    ]
