# Generated by Django 4.2.1 on 2023-06-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiivi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='menu_title_en',
        ),
        migrations.RemoveField(
            model_name='page',
            name='menu_title_fi',
        ),
    ]
