# Generated by Django 4.2.1 on 2023-06-23 07:18

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiivi', '0002_remove_page_menu_title_remove_page_menu_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_fi', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('body', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('body_fi', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('body_en', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('slug', models.SlugField()),
                ('order_by', models.IntegerField(default=0)),
                ('photo', models.FileField(blank=True, default=None, upload_to='members')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
    ]
