# Generated by Django 4.2.1 on 2023-06-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiivi', '0004_alter_member_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='strapline',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='strapline_en',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='strapline_fi',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
