# Generated by Django 4.2.1 on 2023-06-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiivi', '0005_member_strapline_member_strapline_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_order_by', 'title'], 'verbose_name': 'Sivu', 'verbose_name_plural': 'Sivut'},
        ),
    ]
