# Generated by Django 4.2.1 on 2023-06-24 16:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiivi', '0006_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='body_en',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='body_fi',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body_en',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='body_fi',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
