# Generated by Django 4.2.1 on 2023-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiivi', '0007_alter_member_body_alter_member_body_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
