# Generated by Django 4.2.3 on 2023-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kollektiivi', '0010_alter_member_created_by_alter_member_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='pages'),
        ),
    ]
